[2023-12-12T18:04:28.857+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawl_and_store_csv_01.crawl_and_store_csv scheduled__2023-12-11T18:04:18.973118+00:00 [queued]>
[2023-12-12T18:04:28.865+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawl_and_store_csv_01.crawl_and_store_csv scheduled__2023-12-11T18:04:18.973118+00:00 [queued]>
[2023-12-12T18:04:28.865+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-12T18:04:28.878+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): crawl_and_store_csv> on 2023-12-11 18:04:18.973118+00:00
[2023-12-12T18:04:28.885+0000] {standard_task_runner.py:57} INFO - Started process 2351 to run task
[2023-12-12T18:04:28.887+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crawl_and_store_csv_01', 'crawl_and_store_csv', 'scheduled__2023-12-11T18:04:18.973118+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/crawl_and_store_csv.py', '--cfg-path', '/tmp/tmp59fxdgge']
[2023-12-12T18:04:28.891+0000] {standard_task_runner.py:85} INFO - Job 140: Subtask crawl_and_store_csv
[2023-12-12T18:04:28.931+0000] {task_command.py:416} INFO - Running <TaskInstance: crawl_and_store_csv_01.crawl_and_store_csv scheduled__2023-12-11T18:04:18.973118+00:00 [running]> on host 7fd8dd875aa1
[2023-12-12T18:04:28.988+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='xin' AIRFLOW_CTX_DAG_ID='crawl_and_store_csv_01' AIRFLOW_CTX_TASK_ID='crawl_and_store_csv' AIRFLOW_CTX_EXECUTION_DATE='2023-12-11T18:04:18.973118+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-11T18:04:18.973118+00:00'
[2023-12-12T18:04:32.634+0000] {logging_mixin.py:154} INFO - DAG Directory: /opt/***/dags
[2023-12-12T18:04:32.635+0000] {logging_mixin.py:154} INFO - Log Path: /opt/***/dags/camera.csv
[2023-12-12T18:04:32.636+0000] {logging_mixin.py:154} INFO - Current working directory: /opt/***
[2023-12-12T18:04:32.636+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/crawl_and_store_csv.py", line 114, in crawl_and_store_to_csv
    with open(filepath, 'w', newline='', encoding='utf-8') as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/local/camera.csv'
[2023-12-12T18:04:32.648+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=crawl_and_store_csv_01, task_id=crawl_and_store_csv, execution_date=20231211T180418, start_date=20231212T180428, end_date=20231212T180432
[2023-12-12T18:04:32.662+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 140 for task crawl_and_store_csv ([Errno 2] No such file or directory: '/path/to/local/camera.csv'; 2351)
[2023-12-12T18:04:32.676+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-12T18:04:32.690+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
