[2023-12-20T09:53:56.490+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: service_oriented_class_project.insert_safetyWarning manual__2023-12-20T09:53:42.735051+00:00 [queued]>
[2023-12-20T09:53:56.503+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: service_oriented_class_project.insert_safetyWarning manual__2023-12-20T09:53:42.735051+00:00 [queued]>
[2023-12-20T09:53:56.505+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-20T09:53:56.523+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_safetyWarning> on 2023-12-20 09:53:42.735051+00:00
[2023-12-20T09:53:56.537+0000] {standard_task_runner.py:57} INFO - Started process 22797 to run task
[2023-12-20T09:53:56.542+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'service_oriented_class_project', 'insert_safetyWarning', 'manual__2023-12-20T09:53:42.735051+00:00', '--job-id', '590', '--raw', '--subdir', 'DAGS_FOLDER/service_oriented_class_project.py', '--cfg-path', '/tmp/tmp83tzsich']
[2023-12-20T09:53:56.546+0000] {standard_task_runner.py:85} INFO - Job 590: Subtask insert_safetyWarning
[2023-12-20T09:53:56.610+0000] {task_command.py:416} INFO - Running <TaskInstance: service_oriented_class_project.insert_safetyWarning manual__2023-12-20T09:53:42.735051+00:00 [running]> on host f97daee24bd9
[2023-12-20T09:53:56.875+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='christinelee1114@gmail.com' AIRFLOW_CTX_DAG_OWNER='xin' AIRFLOW_CTX_DAG_ID='service_oriented_class_project' AIRFLOW_CTX_TASK_ID='insert_safetyWarning' AIRFLOW_CTX_EXECUTION_DATE='2023-12-20T09:53:42.735051+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-20T09:53:42.735051+00:00'
[2023-12-20T09:53:56.876+0000] {sql.py:274} INFO - Executing: 
            COPY safety_warning(地點位置,管轄警察局,分局,聯繫窗口,聯繫電話,經緯度,經度,緯度)
            FROM 'D:/Airflow-docker/dags/data/safetyWarning_ETL.csv' DELIMITER ',' CSV HEADER;
            
[2023-12-20T09:53:56.883+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-20T09:53:56.890+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-20T09:53:56.928+0000] {sql.py:418} INFO - Running statement: 
            COPY safety_warning(地點位置,管轄警察局,分局,聯繫窗口,聯繫電話,經緯度,經度,緯度)
            FROM 'D:/Airflow-docker/dags/data/safetyWarning_ETL.csv' DELIMITER ',' CSV HEADER;
            , parameters: None
[2023-12-20T09:53:56.932+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFile: could not open file "D:/Airflow-docker/dags/data/safetyWarning_ETL.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2023-12-20T09:53:56.942+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=service_oriented_class_project, task_id=insert_safetyWarning, execution_date=20231220T095342, start_date=20231220T095356, end_date=20231220T095356
[2023-12-20T09:53:56.952+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 590 for task insert_safetyWarning (could not open file "D:/Airflow-docker/dags/data/safetyWarning_ETL.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
; 22797)
[2023-12-20T09:53:56.995+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-20T09:53:57.190+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
