[2023-12-12T15:38:46.511+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawl_and_store_to_mysql_06.insert_sql scheduled__2023-12-11T15:38:22.808266+00:00 [queued]>
[2023-12-12T15:38:46.520+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawl_and_store_to_mysql_06.insert_sql scheduled__2023-12-11T15:38:22.808266+00:00 [queued]>
[2023-12-12T15:38:46.521+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-12T15:38:46.535+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_sql> on 2023-12-11 15:38:22.808266+00:00
[2023-12-12T15:38:46.542+0000] {standard_task_runner.py:57} INFO - Started process 75 to run task
[2023-12-12T15:38:46.546+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crawl_and_store_to_mysql_06', 'insert_sql', 'scheduled__2023-12-11T15:38:22.808266+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/crawl_and_store_to_mysql_06.py', '--cfg-path', '/tmp/tmpbaa48z1h']
[2023-12-12T15:38:46.550+0000] {standard_task_runner.py:85} INFO - Job 117: Subtask insert_sql
[2023-12-12T15:38:46.597+0000] {task_command.py:416} INFO - Running <TaskInstance: crawl_and_store_to_mysql_06.insert_sql scheduled__2023-12-11T15:38:22.808266+00:00 [running]> on host 7fd8dd875aa1
[2023-12-12T15:38:46.656+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='xin' AIRFLOW_CTX_DAG_ID='crawl_and_store_to_mysql_06' AIRFLOW_CTX_TASK_ID='insert_sql' AIRFLOW_CTX_EXECUTION_DATE='2023-12-11T15:38:22.808266+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-11T15:38:22.808266+00:00'
[2023-12-12T15:38:46.657+0000] {sql.py:274} INFO - Executing: 
            COPY cctv_data(location, area, longitude, latitude)
            FROM 'D:/Airflow-docker/dags/data/CCTV.csv' DELIMITER ',' CSV HEADER;
            
[2023-12-12T15:38:46.664+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-12T15:38:46.672+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-12T15:38:46.710+0000] {sql.py:418} INFO - Running statement: 
            COPY cctv_data(location, area, longitude, latitude)
            FROM 'D:/Airflow-docker/dags/data/CCTV.csv' DELIMITER ',' CSV HEADER;
            , parameters: None
[2023-12-12T15:38:46.713+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.CharacterNotInRepertoire: invalid byte sequence for encoding "UTF8": 0xa6
CONTEXT:  COPY cctv_data, line 1

[2023-12-12T15:38:46.721+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=crawl_and_store_to_mysql_06, task_id=insert_sql, execution_date=20231211T153822, start_date=20231212T153846, end_date=20231212T153846
[2023-12-12T15:38:46.733+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 117 for task insert_sql (invalid byte sequence for encoding "UTF8": 0xa6
CONTEXT:  COPY cctv_data, line 1
; 75)
[2023-12-12T15:38:46.760+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-12T15:38:46.773+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
