[2023-12-19T04:35:14.178+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: steal_etl_storeToPostgres.steal_ETL manual__2023-12-19T04:35:13.009272+00:00 [queued]>
[2023-12-19T04:35:14.185+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: steal_etl_storeToPostgres.steal_ETL manual__2023-12-19T04:35:13.009272+00:00 [queued]>
[2023-12-19T04:35:14.186+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-19T04:35:14.197+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): steal_ETL> on 2023-12-19 04:35:13.009272+00:00
[2023-12-19T04:35:14.204+0000] {standard_task_runner.py:57} INFO - Started process 1522 to run task
[2023-12-19T04:35:14.207+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'steal_etl_storeToPostgres', 'steal_ETL', 'manual__2023-12-19T04:35:13.009272+00:00', '--job-id', '378', '--raw', '--subdir', 'DAGS_FOLDER/steal_etl_storeToPostgres.py', '--cfg-path', '/tmp/tmpjpdudc7f']
[2023-12-19T04:35:14.210+0000] {standard_task_runner.py:85} INFO - Job 378: Subtask steal_ETL
[2023-12-19T04:35:14.250+0000] {task_command.py:416} INFO - Running <TaskInstance: steal_etl_storeToPostgres.steal_ETL manual__2023-12-19T04:35:13.009272+00:00 [running]> on host f97daee24bd9
[2023-12-19T04:35:14.449+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='christinelee1114@gmail.com' AIRFLOW_CTX_DAG_OWNER='xin' AIRFLOW_CTX_DAG_ID='steal_etl_storeToPostgres' AIRFLOW_CTX_TASK_ID='steal_ETL' AIRFLOW_CTX_EXECUTION_DATE='2023-12-19T04:35:13.009272+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-19T04:35:13.009272+00:00'
[2023-12-19T04:35:14.470+0000] {warnings.py:109} WARNING - /opt/***/dags/steal_etl_storeToPostgres.py:55: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_loc.drop('_id', axis=1, inplace=True)

[2023-12-19T04:35:14.471+0000] {warnings.py:109} WARNING - /opt/***/dags/steal_etl_storeToPostgres.py:56: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_loc.rename(columns=newcolumns, inplace=True)

[2023-12-19T04:35:14.472+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 171, in _na_arithmetic_op
    result = func(left, right)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py", line 239, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py", line 70, in _evaluate_standard
    return op(a, b)
TypeError: can only concatenate str (not "int") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/steal_etl_storeToPostgres.py", line 59, in steal_etl
    df_loc['日期'] = (df_loc['年'].astype(str) + 1911).astype(str) + df_loc['月'].astype(str) + df_loc['日'].astype(str)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/ops/common.py", line 81, in new_method
    return method(self, other)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/arraylike.py", line 186, in __add__
    return self._arith_method(other, operator.add)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/series.py", line 6112, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/base.py", line 1348, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 232, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)  # type: ignore[arg-type]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 178, in _na_arithmetic_op
    result = _masked_arith_op(left, right, op)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 135, in _masked_arith_op
    result[mask] = op(xrav[mask], y)
TypeError: can only concatenate str (not "int") to str
[2023-12-19T04:35:14.483+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=steal_etl_storeToPostgres, task_id=steal_ETL, execution_date=20231219T043513, start_date=20231219T043514, end_date=20231219T043514
[2023-12-19T04:35:14.491+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 378 for task steal_ETL (can only concatenate str (not "int") to str; 1522)
[2023-12-19T04:35:14.541+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-19T04:35:14.699+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
