[2023-12-12T18:02:03.105+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawl_and_store_csv_01.crawl_and_store_csv manual__2023-12-12T18:02:00.822918+00:00 [queued]>
[2023-12-12T18:02:03.116+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawl_and_store_csv_01.crawl_and_store_csv manual__2023-12-12T18:02:00.822918+00:00 [queued]>
[2023-12-12T18:02:03.117+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-12T18:02:03.131+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): crawl_and_store_csv> on 2023-12-12 18:02:00.822918+00:00
[2023-12-12T18:02:03.142+0000] {standard_task_runner.py:57} INFO - Started process 2306 to run task
[2023-12-12T18:02:03.148+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crawl_and_store_csv_01', 'crawl_and_store_csv', 'manual__2023-12-12T18:02:00.822918+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/crawl_and_store_csv.py', '--cfg-path', '/tmp/tmpeiyedu5m']
[2023-12-12T18:02:03.157+0000] {standard_task_runner.py:85} INFO - Job 138: Subtask crawl_and_store_csv
[2023-12-12T18:02:03.216+0000] {task_command.py:416} INFO - Running <TaskInstance: crawl_and_store_csv_01.crawl_and_store_csv manual__2023-12-12T18:02:00.822918+00:00 [running]> on host 7fd8dd875aa1
[2023-12-12T18:02:03.279+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='xin' AIRFLOW_CTX_DAG_ID='crawl_and_store_csv_01' AIRFLOW_CTX_TASK_ID='crawl_and_store_csv' AIRFLOW_CTX_EXECUTION_DATE='2023-12-12T18:02:00.822918+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-12T18:02:00.822918+00:00'
[2023-12-12T18:02:07.062+0000] {logging_mixin.py:154} INFO - DAG Directory: /opt/***/dags
[2023-12-12T18:02:07.063+0000] {logging_mixin.py:154} INFO - Log Path: /opt/***/dags/camera.csv
[2023-12-12T18:02:07.065+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/crawl_and_store_csv.py", line 113, in crawl_and_store_to_csv
    with open(filepath, 'w', newline='', encoding='utf-8') as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/local/camera.csv'
[2023-12-12T18:02:07.080+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=crawl_and_store_csv_01, task_id=crawl_and_store_csv, execution_date=20231212T180200, start_date=20231212T180203, end_date=20231212T180207
[2023-12-12T18:02:07.091+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 138 for task crawl_and_store_csv ([Errno 2] No such file or directory: '/path/to/local/camera.csv'; 2306)
[2023-12-12T18:02:07.140+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-12T18:02:07.153+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
